apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: chronocollector-ksm
  name: chronocollector-ksm
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: chronocollector-ksm
  name: chronocollector-ksm
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - get
    - list
    - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: chronocollector-ksm
  name: chronocollector-ksm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chronocollector-ksm
subjects:
- kind: ServiceAccount
  name: chronocollector-ksm
  namespace: default
---
apiVersion: v1
data:
  config.yml: |
    logging:
      level: ${LOGGING_LEVEL:info}

    metrics:
      scope:
        prefix: "chronocollector"
      prometheus:
        handlerPath: /metrics
      sanitization: prometheus
      samplingRate: 1.0
      extended: none

    listenAddress: "${LISTEN_ADDRESS:0.0.0.0:3030}"

    labels:
      defaults:
        tenant_k8s_cluster: ${KUBERNETES_CLUSTER_NAME:""}

    backend:
      type: ${BACKEND_TYPE:gateway}
      gateway:
        address: ${GATEWAY_ADDRESS:""}
        insecure: ${GATEWAY_INSECURE:false}
        cert: ${GATEWAY_CERT:""}
        certSkipVerify: ${GATEWAY_CERT_SKIP_VERIFY:false}

    kubernetes:
      client:
        outOfCluster: ${KUBERNETES_CLIENT_OUT_OF_CLUSTER:false}
      processor:
        annotationsPrefix: ${KUBERNETES_PROCESSOR_ANNOTATIONS_PREFIX:"prometheus.io/"}

    discovery:
      kubernetes:
        enabled: true
        serviceMonitorsEnabled: true
        endpointsDiscoveryEnabled: true
        useEndpointSlices: true
        kubeSystemEndpointsDiscoveryEnabled: true
        podMatchingStrategy: service_monitors_only
      prometheus:
        enabled: true
        scrape_configs:
          - job_name: 'chronocollector'
            scrape_interval: 30s
            scrape_timeout: 30s
            static_configs:
              - targets: ['localhost:3030']
            relabel_configs:
              - target_label: "instance"
                replacement: ${KUBERNETES_POD_NAME:""}
                action: replace

    scrape:
      defaults:
        scrapeInterval: "30s"
        scrapeTimeout: "30s"

    serviceMonitor:
      allowSkipPodInfo: true
      serviceMonitorSelector:
        matchAll: false
        matchExpressions:
          - label: app.kubernetes.io/name
            operator: In
            values:
              - kube-state-metrics
kind: ConfigMap
metadata:
  labels:
      app: chronocollector-ksm
  name: chronocollector-ksm
  namespace: default
---
apiVersion: v1
data:
  address: <add-base64-encoded-token-here>
  api-token: <add-base64-encoded-token-here>
kind: Secret
metadata:
  labels:
    app: chronocollector-ksm
  name: chronocollector-ksm
  namespace: default
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chronocollector-ksm
  name: chronocollector-ksm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronocollector-ksm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3030"
        prometheus.io/scrape: "true"
      labels:
        app: chronocollector-ksm
    spec:
      containers:
      - env:
        - name: LISTEN_ADDRESS
          value: 0.0.0.0:3030
        - name: GATEWAY_ADDRESS
          valueFrom:
            secretKeyRef:
              key: address
              name: chronocollector-ksm
        - name: LOGGING_LEVEL
          value: info
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              key: api-token
              name: chronocollector-ksm
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_CLUSTER_NAME
          value: default
        - name: KUBERNETES_KUBELET_MONITORING_ENABLED
          value: "false"
        - name: KUBERNETES_POD_NAME
          valueFrom:
           fieldRef:
             fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/chronosphereio/chronocollector:v0.100.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: chronocollector-ksm
        ports:
        - containerPort: 3030
          name: http
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 1000m
            memory: 512Mi
        volumeMounts:
        - mountPath: /etc/chronocollector
          name: chronocollector-ksm
      serviceAccountName: chronocollector-ksm
      terminationGracePeriodSeconds: 5
      tolerations:
      - operator: Exists
      volumes:
      - configMap:
          name: chronocollector-ksm
        name: chronocollector-ksm
